### ISSUE TITLE
CHORE: 티켓팅신청 성공시 뜨는 모달 대사 변경

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/danfesta#12]
![image](https://user-images.githubusercontent.com/68864422/236194840-c31d6185-a623-4351-8b63-57b2fc6d8657.png)

17/18 (1일차/2일차) 단국존 티켓 신청이 성공적으로 완료되었습니다.
내부적으로 검토 이후 선착순 1200명에 선정되어 티켓팅 성공한 경우 1~2일 내로 에 티켓팅 승인 결과가 등록된 휴대전화번호의 SMS로 전송됩니다.

티켓팅 번호: 5884번

**Comment by ho991217** [comment]
이런건 앞으로 디자인 단계에서 바꾸세요
