### ISSUE TITLE
[FIX] “티켓팅 창에서 하단 티켓 퀵드로우바 클릭시 셀렉트 탭 표시 오류에 관한 이슈 리포트”

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/danfesta#13]
**Describe the bug**
파란색이 날라다님 하단 1일차 2일차 부분이 날라다님

**To reproduce**
버그 재현 방법:
1. 모든 페이지
2. `Scroll down to 가장 위로 스크롤 하면 정상적으로 뜸 하지만, 조금이라도 내린다면? 1일차 2일차부분이 날라다님
3. `Click on 하단 티켓 확인 or 메인화면의 상단 티켓확인`

버그? 또는 의도? 이건 Question 재현 방법:
1. 라인업, 티켓팅 페이지 처럼 상단에 아래 사진이 있는 페이지
![image](https://user-images.githubusercontent.com/68864422/236202494-b5263a83-ee37-45e1-87e6-7e414982672e.png)
2. 하단 티켓조회 버튼 클릭 후 닫기
3. 파란색이 밑에서 날라다님

https://user-images.githubusercontent.com/68864422/236201356-d44a837d-0631-42da-a46a-9d1893aae1f0.mp4

**Comment by ho991217** [comment]
이쁘네요
