### ISSUE TITLE
[TEST] Ticketing 관련  TEST 페이지 요청

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/danfesta#14]
Describe the new feature

마감 기한: 2023-05-12 19:00시 까지
작업 내용: 
13일 Ticketing 전 모든 기능들이 정상 작동하는지 확인하기 위한 테스트 페이지가 필요.
Ticketing Test는
12일 20시 10분(17일) 20시 20분(18일) 을 진행하여
#8  이 구현되었다면, 기간 전에 티켓팅 페이지가 접속이 되는지
아니라면 티켓팅이 되는지 확인
및 재학생이 아닌 경우의 티켓팅 체크, 중복 티켓팅 확인 등

Todos:

- [ ] Route 명: /ticketing/test/
- [x] 화면 내에 테스트 페이지임을 강요하는 문구가 필요 (총학 내부에서 유포하여 문제 발생 방지)
- [x] 17일차, 18일차 두개 모두 진행
- [x] 다음의 issue 사항도 적용되면 best #8

**Comment by ho991217** [comment]
기존 route 적용하여
`/ticketing/test/`로 진행 하겠습니다.

**Comment by developerChans** [comment]
라우트 새로 안만들고 develop branch를 로컬에서 올리는 방식으로 진행
